spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    PASSWORD: sa
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret

springdoc:
  api-docs:
    path: /api-docs